### ISSUE TITLE
this plugin cannot be run under WSL?

### ISSUE THREAD

**Issue by n3rd4i** [technosophos/vscode-make#5]
the issue currently is that is not possible to change the "default" expected shell, to WSL one.
maybe in future releases, it would be possible to select this based on the VSCode default shell? (which could be bash-in-windows)

**Comment by Kai-Richardson** [comment]
@n3rd4i No idea if this is still an issue for you, but this works for me under WSL and using the VSCode feature to remote into it.

**Comment by n3rd4i** [comment]
thanks will try that, will close this.
